services:
  qtcreator:   
    image: ${QTCREATOR_IMAGE_NAME:-zanyxdev/5.15.8-qtcreator:v15.0.0}  
    depends_on:
      init-setup:
        condition: service_completed_successfully   
    build:                
      context: .
      args:   
        # Используем переменные окружения хоста, которые нужно вычислить заранее
        QT_VERSION: ${QT_VERSION_SHORT}
        LANG: "ru-RU.UTF-8"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        CMAKE_URL: ${CMAKE_URL}
        QTCREATOR_URL: ${QTCREATOR_URL}    
        CMDTOOLS_URL: ${CMDTOOLS_URL}
    container_name: qtcreator-dev
    environment:
      - TERM=xterm-256color
      #- XDG_RUNTIME_DIR=/tmp/runtime-developer
      - XDG_RUNTIME_DIR=/run/user/${USER_ID:-1000}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
      - XAUTHORITY=$XAUTH
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - GPG_TTY=/dev/console
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulseaudio.cookie
      - $XSOCK:$XSOCK
      - $XAUTH:$XAUTH
      - src-volume:/usr/local/src
      - opt-volume:/opt
      - ccache-volume:/ccache
      - type: bind
        source: $HOME/qtcreator-app
        target: /home/developer    
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    init: true  
    command: bash 
         
  # Pre run setup (профиль "init")
  init-setup:
  # Используем тот же образ, что уже собран/скачан, 
  # чтобы не собирать Dockerfile второй раз
    image: ${QTCREATOR_IMAGE_NAME:-zanyxdev/5.15.8-qtcreator:v15.0.0}
    user: "root:root"
    build:                
      context: .
    environment:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - LANG=ru-RU.UTF-8
        - CMAKE_URL= ${CMAKE_URL}
        - QTCREATOR_URL=${QTCREATOR_URL}    
        - CMDTOOLS_URL=${CMDTOOLS_URL}            
    volumes:
      - ${PWD}/init.sh:/root/init.sh 
      - src-volume:/usr/local/src
      - opt-volume:/opt
      - ccache-volume:/ccache
    #Checking git clone sources and pre build
    entrypoint: []               # ← Ключевая строка: отключаем ENTRYPOINT образа
    command: ["sh", "-c", "/root/init.sh"]
       
    # Гарантируем, что контейнер не будет перезапускаться после выполнения
    restart: "no" 
volumes:
  src-volume:
    name: ${SRC_VOLUME_NAME}
  opt-volume:
    name: ${OPT_VOLUME_NAME}
  ccache-volume:
    name: ${CCACHE_VOLUME}  
      
